apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "podpulse.fullname" . }}-detector
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "podpulse.labels" . | nindent 4 }}
    app.kubernetes.io/component: detector
spec:
  replicas: {{ .Values.detector.replicas }}
  selector:
    matchLabels:
      {{- include "podpulse.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: detector
  template:
    metadata:
      labels:
        {{- include "podpulse.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: detector
    spec:
      serviceAccountName: {{ include "podpulse.serviceAccountName" . }}
      containers:
        - name: detector
          image: {{ include "podpulse.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/local/bin/pp-detector"]
          ports:
            - name: grpc
              containerPort: {{ .Values.detector.service.grpcPort }}
            - name: http
              containerPort: {{ .Values.detector.service.httpPort }}
          env:
            - name: POSTGRES_DSN
              value: {{ .Values.postgres.dsn | quote }}
            - name: CLICKHOUSE_DSN
              value: {{ .Values.clickhouse.dsn | quote }}
            {{- if .Values.alerts.slack.webhook }}
            - name: SLACK_WEBHOOK
              value: {{ .Values.alerts.slack.webhook | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.detector.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
              scheme: HTTPS
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "podpulse.fullname" . }}-detector
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "podpulse.labels" . | nindent 4 }}
    app.kubernetes.io/component: detector
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: {{ .Values.detector.service.grpcPort }}
      targetPort: grpc
    - name: http
      port: {{ .Values.detector.service.httpPort }}
      targetPort: http
  selector:
    {{- include "podpulse.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: detector
